appspec.yml
version: 0.0
os: linux
files:
  - source: application.jar
    destination: /var/app/current/
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
